### ISSUE TITLE
Unable to install with Visual Studio for Mac

### ISSUE THREAD

**Issue by JordanTHarris** [hifi/monodevelop-justenoughvi#54] opened 2017-05-14 06:02 UTC
This is what I get when trying to install it on VS for Mac from file. Is it possible to make it compatable?
<img width="427" alt="screen shot 2017-05-14 at 2 00 25 am" src="https://cloud.githubusercontent.com/assets/11206202/26031637/25eccaea-3849-11e7-9b15-81dc55f253bf.png">

**Comment by hifi** [comment] 2017-05-14 06:15
Duplicate of #42. For the time being, I have no access to VS for Mac and MonoDevelop does not have a 7.x release for other platforms.

It could possibly build against VS for Mac if someone gave it a shot if Add-In Maker is also supported.

**Closed as completed by hifi** 2017-05-14 06:15 UTC
